version: "4"
services:
  HubService:
    image: selenium/hub
    container_name: selenium-hub-pc
    ports:
      - "4445:4444"
      - "4442:4442"
      - "4443:4443"

  ChromeService1:
    image: selenium/node-chrome
    container_name: selenium-node-chrome
    shm_size: "2gb"
    ports:
      - "5900"
      - "7900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub-pc
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_MAX_INSTANCES=3
    depends_on:
      - HubService